# Generated by Django 5.2.9 on 2026-05-21 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_motorstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Unique hardware identifier (e.g., MAC address or Node ID)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human readable name of the device or field', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Physical location of the sensor', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='motorstate',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motor_state', to='iot.device'),
        ),
        migrations.AddField(
            model_name='soilmoisture',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='iot.device'),
        ),
    ]
