# Generated by Django 5.2.9 on 2025-12-23 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoisture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='Main data field for soil moisture information')),
                ('metadata', models.JSONField(blank=True, help_text='Optional metadata field', null=True)),
                ('ip_address', models.CharField(help_text='IP address of the data source', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SoilMoisture',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='SoilMoistur_created_a0f66c_idx'), models.Index(fields=['ip_address'], name='SoilMoistur_ip_addr_c54609_idx')],
            },
        ),
    ]
