# Generated by Django 5.2.9 on 2025-12-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil_moisture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
